### ISSUE TITLE
Vector instance of Keyed has a definition of index that loops indefinately.

### ISSUE THREAD

**Issue by recursion-ninja** [ekmett/vector-instances#6]
I ran into an issue where my program ended in an exception from the RTS reporting an infinite loop:

    me@box~$ ./prog
    prog: <<loop>>

I recompiled and ran with profiling enabled to track down the source  of the problem and got the following output:

    me@box~$ ./prog +RTS -xc -RTS
    ...
    called from Data.Vector.Instances.CAF:$fIndexableVector_$cindex
    pcg: <<loop>>

I replicated the issue by doing the following:

    me@box~$ ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.10.2
    me@box~$ git clone git://github.com/ekmett/vector-instances.git
    me@box~$ cd vector-instances
    me@box~$ cabal sandbox init
    me@box~$ cabal configure
    me@box~$ cabal install
    me@box~$ cabal repl
    [1 of 1] Compiling Data.Vector.Instances ( src/Data/Vector/Instances.hs, interpreted )
    Ok, modules loaded: Data.Vector.Instances.
    *Data.Vector.Instances> import Data.Vector (Vector,fromList)
    *Data.Vector.Instances Data.Vector> import qualified Data.Vector as V ((!))
    *Data.Vector.Instances Data.Vector V> fromList [0..5] V.! 3
    3
    *Data.Vector.Instances Data.Vector V> fromList [0..5] ! 3
    (never terminates)

**Comment by recursion-ninja** [comment]
This [pull request](https://github.com/ekmett/vector-instances/pull/7) should fix the issue.

**Comment by k-bx** [comment]
@ekmett this is a pretty severe one, would you please check it out? Taking an index of a `Vector` loops infinitely. Thank you!

**Comment by ekmett** [comment]
Merged that pull request.

**Comment by k-bx** [comment]
@ekmett sorry for bothering once again, but could you please make a hackage release? Thanks again!
